export type ClickSignature = '1_4' | '3_4' | '4_4' | '6_8';

export interface ClickMeta {
  signature: ClickSignature;
  bpm: number;
  /** Offset of the first downbeat, in milliseconds. Can be negative. */
  offsetMs: number;
}

/** Interleaved min/max envelope: `min[i]`/`max[i]` for bucket i. */
export interface PeakData {
  min: Float32Array;
  max: Float32Array;
}

export interface AudioTrack {
  id: string;
  name: string;
  /** Original file. Absent for generated click tracks. */
  file?: File;
  volume: number; // 0.0 to 1.0
  isMuted: boolean;
  isSolo: boolean;
  duration: number;
  /** Decoded audio, always at the shared AudioContext's sample rate. */
  audioBuffer?: AudioBuffer;
  /** Precomputed envelope for waveform drawing. */
  peaks?: PeakData;
  status: TrackStatus;
  error?: string;
  isClick?: boolean; // Excluded from global pitch shift when true
  clickMeta?: ClickMeta; // Present only for tracks generated by the click generator
}

export interface PlaybackState {
  isPlaying: boolean;
  currentTime: number;
  duration: number;
  isExporting: boolean;
}

export interface TempoAnalysis {
  bpm: number;
  /** Time of the first detected beat, in seconds. */
  firstBeatS: number;
  /** 0..1 — how strongly the onset envelope agrees with the detected grid. */
  confidence: number;
}

export type TrackStatus = 'loading' | 'ready' | 'error';
